[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ["py310"]
exclude='\.git|\.tox'

[tool.isort]
profile = "black"
line_length = 100
force_sort_within_sections = true
combine_as_imports = true

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
