[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ImageDePHI"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "tifftools",
]

[project.scripts]
imagedephi = "imagedephi:main"

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
line_length = 100
force_sort_within_sections = true
combine_as_imports = true

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/stubs"

[tool.pyright]
stubPath = "stubs"
