[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ImageDePHI"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "click",
    "tifftools",
    "fastapi",
    "python-multipart",
    "Jinja2",
    "hypercorn",
    "pyyaml",
]

[project.scripts]
imagedephi = "imagedephi.main:imagedephi"

[tool.setuptools.packages.find]
include = ["imagedephi*"]

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
force_sort_within_sections = true
combine_as_imports = true

[tool.mypy]
ignore_missing_imports = true
show_error_codes = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/stubs"
exclude = [
    "build/",
]

[tool.pyright]
stubPath = "stubs"

[tool.djlint]
extension = "html.j2"
profile = "jinja"
indent = 2
