name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      # Seeing whether a failure is exclusive to one platform is useful
      fail-fast: false
      matrix:
        os:
          # Use an older Linux: https://pyinstaller.org/en/stable/usage.html#making-gnu-linux-apps-forward-compatible
          - ubuntu-20.04
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Run tests
        run: |
          tox
      - name: Build binary
        run: |
          tox -e binary
      - name: Test binary runs
        run: |
          dist/imagedephi --help
      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: imagedephi-${{ matrix.os }}-binary
          path: |
            dist/imagedephi
            dist/imagedephi.exe
          retention-days: 5
          if-no-files-found: error
