---
name: release
on:
  release:
    types:
      - published
jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # Use an older Linux: https://pyinstaller.org/en/stable/usage.html#making-gnu-linux-apps-forward-compatible
          - ubuntu-20.04
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # LFS data is not needed for release
          lfs: false
          # Tags are needed to compute the current version number
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Build binary
        run: |
          tox -e binary
      - name: Zip and upload binary
        run: |
          .github/zip_and_upload_package.sh ${{ runner.os }} ${{ github.event.release.tag_name }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
